
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>添加文章</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/statics/css/bootstrap.min.css">
   
    <!-- Custom styles for this template -->
    <link href="/statics/css/narrow-jumbotron.css" rel="stylesheet">

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link active" href="#">主页 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">关于</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">联系我们</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">添加文章</h3>
      </div>

      <div class="jumbotron">
        <p class="lead"> 
		<label class="sr-only" for="input_title">标题</label> 
		<input id="input_title" name="title" placeholder="请输入标题" class="form-control" type="text"> 
		<label class="sr-only" for="input_content">内容</label> 
		<input id="input_content" name="content" placeholder="请输入内容" class="form-control" type="text"> 
		</p>
        <p><a class="btn btn-lg btn-success" id="testBtn" role="button">确认</a></p>
      </div>



      <footer class="footer">
        <p>&copy; Huang Kunlun 2017</p>
      </footer>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/statics/js/jquery-3.1.1.min.js" ></script>
	<script src="/statics/js/tether.min.js"></script>
	<script src="/statics/js/bootstrap.min.js"></script>
	<script src="/statics/js/hiplonsys.js" type="text/javascript"></script>

	<script src="/statics/js/testrouter.js" type="text/javascript"></script>
	
  </body>
</html>
